# Generated by Django 4.0.5 on 2022-10-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data',
        ),
    ]
