# Generated by Django 4.0.5 on 2022-10-11 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctapp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='fdata',
        ),
    ]
