# Generated by Django 4.0.5 on 2022-10-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctapp', '0004_delete_fdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='fdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('calories', models.IntegerField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
            ],
        ),
    ]
